// config.h - generated by premake
// do not edit by hand, instead edit config.lua and regenerate
// it is important that you use premake recreate this file if changing xml parsers or codecs for the static builds
#define CEGUI_HAS_FREETYPE 
#define CEGUI_CODEC_FREEIMAGE 1
#define CEGUI_TINYXML_NAMESPACE CEGUITinyXML
#define CEGUI_DEFAULT_IMAGE_CODEC FreeImageImageCodec
#define CEGUI_HAS_DEFAULT_LOGGER 
#define CEGUI_TINYXML_H "ceguitinyxml/tinyxml.h"
#define CEGUI_SAMPLES_USE_OGRE 
#define CEGUI_WITH_TINYXML 1
#define CEGUI_DEFAULT_XMLPARSER TinyXMLParser
#define CEGUI_FALAGARD_RENDERER 
#define CEGUI_LUA_VER 51
#if defined(_DEBUG) || defined(DEBUG)
#   define CEGUI_HAS_BUILD_SUFFIX
#   define CEGUI_BUILD_SUFFIX "_d"
#endif
